name: Build Debian Source Package

on:
  workflow_call:
  push:
    branches:
      - developer
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-debian-src:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: mpwrd-menu

      - name: Install deps
        shell: bash
        working-directory: mpwrd-menu
        run: |
          sudo apt-get update -y --fix-missing
          sudo apt-get install -y software-properties-common build-essential devscripts equivs
          sudo mk-build-deps --install --remove --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control

      - name: Package debian source
        working-directory: mpwrd-menu
        run: debuild -S -nc -us -uc

      - name: Store binaries as an artifact
        uses: actions/upload-artifact@v6
        with:
          name: mpwrd-menu-src
          overwrite: true
          path: |
            mpwrd-menu_*
